#ifndef GMTKJAM21_FIRSTNAME_H
#define GMTKJAM21_FIRSTNAME_H

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "rhc/error.h"

#define FIRSTNAME_MAX_LENGTH 16

//#define LENGTH_TEST

// out_name should be a buffer with at least FIRSTNAME_MAX_LENGTH+1 bytes (null terminator)
static void firstname_generate(char *out_name) {
    const char *pre[] = {
            "super",
            "Super",
            "SUPEr",
            "ultra",
            "ULTRa",
            "MEGA ",
            "Mega ",
            "mini ",
            "micro",
            "nano",
            "MC ",
            "King ",
            "Queen",
            "Frau ",
            "littl",
            "BIG ",
            "DJ ",
            "Sir ",
            "Mr ",
            "Ms ",
            "Mrs ",
            "Lady ",
            "Ober ",
            "cRaZy",
            "fREAk",
            "Spass",
            "Dr. ",
            "Ing. ",
            "Prof.",
            "Lord ",
            "Magic",
            "Hello",
            "Great",
            "asi ",
            "Alpha",
            "blue ",
            "red ",
            "fun ",
            "nice ",
            "smoky",
            "hot ",
            "HOT ",
            "cool ",
            "COOL ",
            "Baby ",
            "Star ",
            "sexy ",
            "",
            ""
    };
    size_t pre_len = sizeof pre / sizeof *pre;
#ifdef LENGTH_TEST
    for (int i = 0; i < pre_len; i++)
        assume(strlen(pre[i]) <= 5, "wtf");
#endif

    const char *mid[] = {
            "Wolfgang",
            "Hermann ",
            "Seppl ",
            "Thommy ",
            "Artur ",
            "Hannes ",
            "Lutz ",
            "Klaas ",
            "Billy ",
            "Andy ",
            "Kati ",
            "Chris ",
            "Andreas ",
            "Sebi ",
            "Susi ",
            "Susie ",
            "Beate ",
            "Pupsi ",
            "Jake ",
            "Marie ",
            "Leonie ",
            "Stella ",
            "Kathrin ",
            "Kathi ",
            "Kai ",
            "Jonas ",
            "Lukas ",
            "Lucas ",
            "Schlaubi",
            "Arschi ",
            "Streber ",
            "Pussy ",
            "Hund ",
            "Katze ",
            "Tiger ",
            "Ewald ",
            "Marlies ",
            "Ludwig ",
            "Borat ",
            "Mats ",
            "James ",
            "Jack ",
            "Tina ",
            "Horst ",
            "Max ",
            "Kirsten ",
            "Olaf ",
            "Elsa ",
            "Anna ",
            "Christof",
            "Jan ",
            "Norbert ",
            "Fabian ",
            "Andre ",
            "Niklas ",
            "Vogel ",
            "Noah ",
            "Felix ",
            "Piet ",
            "Basti ",
            "Schatzi ",
            "Hasi ",
            "Wolfi ",
            "Mausi ",
            "Kamin ",
            "Bob ",
            "Magic ",
            "Mike ",
            "XXL ",
            "Artur ",
            "Ben ",
            "Jesus ",
            "Gott ",
            "Alfons ",
            "Edith ",
            "Sophie ",
            "Gregor ",
            "Petra ",
            "Ludger ",
            "Edith ",
            "Anne ",
            "Dominik ",
            "Henrik ",
            "Klara ",
            "Rosa ",
            "Lena ",
            "Nele ",
            "Nino ",
            "Johanna ",
            "Maja ",
            "Charly ",
            "Milan ",
            "Stephen ",
            "Jana ",
            "Steffi ",
            "Nick ",
            "Ulrich ",
            "Jutta ",
            "Kitty ",
            "World ",
            "Muscle ",
            "Sexy ",
            "Leona ",
            "Dieter ",
            "Detlef ",
            "Mickey ",
            "Merle ",
            "Nadja ",
            "Justin ",
            "Conny ",
            "Ruth ",
            "Rebecka ",
            "Elias ",
            "Viktor ",
            "Wodka ",
            "Bombasti",
            " (.)(.) ",
            " 8====D ",
            "Robert ",
            "Schmidt ",
            "Merkel ",
            "Fischer ",
            "Gauner ",
            "Sterni ",
            "Joachim ",
            "Mario ",
            "Peach ",
            "Luigi ",
            "Fuchs ",
            "Ente ",
            "Schlumpf",
            "Schmusi ",
            "Lutscher",
            "Lusche ",
            "Alki ",
            "Smoker ",
            "Dulli ",
            "Bubi ",
            "Klaus ",
            "Joko ",
            "Pikachu ",
            "Banane ",
            "Hansi ",
            "Hannes ",
            "Franz ",
            "Schoko ",
            "Gunter ",
            "Katja ",
            "Sven ",
            "Aladdin ",
            "Homer ",
            "Kevin ",
            "Jasmin ",
            "Silvia ",
            "Angie ",
            "Kiffer ",
            "Baby"

    };
    size_t mid_len = sizeof mid / sizeof *mid;
#ifdef LENGTH_TEST
    for (int i = 0; i < mid_len; i++)
        assume(strlen(mid[i]) <= 8, "wtf");
#endif


    const char *post[] = {
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "00",
            "01",
            "02",
            "03",
            "04",
            "05",
            "06",
            "07",
            "08",
            "09",
            "007",
            "69",
            "420",
            ":D",
            ";D",
            ":P",
            ";P",
            ":-*",
            ";-*",
            "._.",
            "???",
            "#0",
            "#1",
            "#2",
            "#3",
            "#4",
            "#5",
            "#6",
            "#7",
            "#8",
            "#9",
            "xD",
            "xP",
            "xXx",
            "123",
            "987",
            "555",
            "666",
            "383",
            "900",
            "100",
            "DDR",
            "USA",
            "DE",
            "EN",
            "FR",
            "NL",
            ".",
            "..",
            "...",
            ".:.",
            ":.:",
            ":::",
            " <3",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
    };
    size_t post_len = sizeof post / sizeof *post;
#ifdef LENGTH_TEST
    for (int i = 0; i < post_len; i++)
        assume(strlen(post[i]) <= 3, "wtf");
#endif

    // random choice
    srand(time(NULL));

    const char *used_pre = pre[rand() % pre_len];
    const char *used_mid = mid[rand() % mid_len];
    const char *used_post = post[rand() % post_len];

    snprintf(out_name, FIRSTNAME_MAX_LENGTH + 1, "%s%s%s", used_pre, used_mid, used_post);

    // strip spaces right
    char *it = out_name + (strlen(out_name) - 1);
    while (it > out_name && *it == ' ')
        *it-- = '\0';
}

#endif //GMTKJAM21_FIRSTNAME_H
